name: travelex
description: Travelex App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.2
  firebase_core: ^1.7.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.4
  firebase_messaging: ^10.0.8
  firebase_analytics: ^9.1.0
  #firebase packages
  syncfusion_flutter_maps: ^19.4.38-beta
  flutter_native_splash: ^1.3.2
  sqflite: ^2.0.0+3
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  bottom_navy_bar: ^5.6.0
  fab_circular_menu: ^1.0.0
  flutter_material_color_picker: ^1.1.0+2
  fluttertoast: ^8.0.8
  sizer: ^2.0.13
  shared_preferences: ^2.0.11
  country_picker: ^2.0.9
  animate_do: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  cupertino_icons: ^1.0.4
  step_progress_indicator: ^1.0.1
  flag: ^5.0.1
  cached_network_image: ^3.2.0
  shadowed_image: ^1.0.3
  multi_image_picker2: ^5.0.2
  image_picker: ^0.8.4+4
  dart_countries: ^2.1.0
  # panorama: ^0.4.1
  flutter_screenutil: ^5.5.3+2
  adaptive_theme: ^2.3.0
  custom_switch: ^0.0.1
  auto_direction: ^0.0.5
  animated_text_kit: ^4.2.1
  lottie: ^1.2.1
  url_launcher: ^6.0.18
  # youtube_player_flutter: ^8.0.0
  # video_player: ^2.3.0
  shimmer: ^2.0.0
  flutter_staggered_animations: "^1.0.0"
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  path_provider: ^2.0.8
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0

module:
  androidX: true # Add this line

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/travelex-icon.ico"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/svg/
    - assets/geo_json/
    - assets/icons/
    - assets/images/
    - assets/others/

  fonts:
    - family: Curvs
      fonts:
        - asset: assets/fonts/curvs.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Sans
      fonts:
        - asset: assets/fonts/Sans.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta.ttf

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf
